[Settings]
  ID="63754294-deec-4e57-821e-6a1676917198"

[build]
  base = "client/"
  publish = "client/build/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
